name = "module-replacements"
compatibility_date = "2025-02-14"
main = "./.output/server/index.mjs"
assets = { directory = "./.output/public/", binding = "ASSETS" }

[[kv_namespaces]]
binding = "default"
id = "5eac8b4b7b354f8ca86789ef9468de8e"
preview_id = "module-replacements-default"

[triggers]
crons = ["0 * * * *"]
